// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3wSuyd79-z-HVWVYHLGlrJZbfLki--DY',
    appId: '1:958725257859:web:cf1068278dd4482b8db9b6',
    messagingSenderId: '958725257859',
    projectId: 'fasum-app-3fbac',
    authDomain: 'fasum-app-3fbac.firebaseapp.com',
    databaseURL: 'https://fasum-app-3fbac-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-3fbac.appspot.com',
    measurementId: 'G-DVVTCZDN9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzJJ-cSFcUQz65Y4KdwEjWSRJTjNNmWA8',
    appId: '1:958725257859:android:6e0d24fc784b4f888db9b6',
    messagingSenderId: '958725257859',
    projectId: 'fasum-app-3fbac',
    storageBucket: 'fasum-app-3fbac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEMlf6MVJZIavgkRMi-T0ugTFfhEHOZXY',
    appId: '1:958725257859:ios:60dbbe5e68632fa88db9b6',
    messagingSenderId: '958725257859',
    projectId: 'fasum-app-3fbac',
    databaseURL: 'https://fasum-app-3fbac-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-3fbac.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEMlf6MVJZIavgkRMi-T0ugTFfhEHOZXY',
    appId: '1:958725257859:ios:ca48a965755415258db9b6',
    messagingSenderId: '958725257859',
    projectId: 'fasum-app-3fbac',
    databaseURL: 'https://fasum-app-3fbac-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-3fbac.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
